output: Reference
clean: false
sdk: iphone
author: Napster
author_url: http://lo-music.ru
module: lo.music
readme: README.md
min_acl: private
theme: fullwidth

custom_categories:
  - name: Application
    children:
      - AppDelegate

  - name: Utilities
  	children:
  	  - Log
  	  - LogType

