excluded:
  - Carthage
  - Pods
  - Sources/Extensions/SwiftyJSON.swift
  - Sources/Extensions/Reachability.swift

disabled_rules:
  - nesting
  - void_return
  - unused_optional_binding

opt_in_rules:
  - attributes
  - force_unwrapping
  - object_literal
  - private_outlet
  - empty_count
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalesing
  - switch_case_on_newline
  - empty_count
  - redundant_nil_coalescing
  - nimble_operator
  - closure_end_indentation
  - file_header
  - first_where
  - prohibited_super_call
  # - operator_usage_whitespace
  # - number_separator
  # - missing_docs
  # - closure_spacing
  # - conditional_returns_on_newline

vertical_whitespace:
  max_empty_lines: 3
file_length:
  warning: 500
  error: 1000
line_length:
  warning: 200
  error: 250
function_body_length:
  warning: 100
  error: 150
variable_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 40
    error: 60
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 40
    error: 60
statement_position:
  statement_mode: uncuddled_else
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
colon:
  flexible_right_spacing: true
